name: allasone
favicon: null
layout_spectrum: 0.7109155389480293
typography_spectrum: 0.6485934467054904
title: gather and share news of love and inspiration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8848885234910995
  lightness: 0.7336980530526489
  saturation: 0.934031778248027
  rhythmicContrast: 0.5702265328727663
purpose: []
